export const productCatalog = [
  {
    title: 'Smart Door Lock Pro X',
    description: 'WiFi-enabled smart lock with fingerprint and mobile app access.',
    price: 249,
    stock: 34,
    category: 'Door & Lock Services',
    brand: 'DoorSetFix',
    images: ['https://images.unsplash.com/photo-1558002038-1055907df827?w=1200'],
  },
  {
    title: 'Video Doorbell 2K',
    description: 'AI motion detection with cloud storage and two-way audio.',
    price: 189,
    stock: 48,
    category: 'Home Security',
    brand: 'SecureHome',
    images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200'],
  },
  {
    title: 'Digital Keypad Deadbolt',
    description: 'Keyless deadbolt with temporary access codes and auto-lock.',
    price: 129,
    stock: 57,
    category: 'Door & Lock Services',
    brand: 'LockGuard',
    images: ['https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200'],
  },
  {
    title: 'HVAC Smart Thermostat',
    description: 'Energy-saving thermostat with room-by-room scheduling.',
    price: 219,
    stock: 22,
    category: 'HVAC & AC Repair',
    brand: 'ClimaSense',
    images: ['https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=1200'],
  },
  {
    title: 'Plumbing Leak Detector Kit',
    description: 'Real-time leak alerts and automatic shutoff compatibility.',
    price: 159,
    stock: 41,
    category: 'Plumbing Services',
    brand: 'FlowSafe',
    images: ['https://images.unsplash.com/photo-1521207418485-99c705420785?w=1200'],
  },
  {
    title: 'Electrical Tool Bundle',
    description: 'Professional electrician toolset for home and commercial jobs.',
    price: 99,
    stock: 63,
    category: 'Electrical Services',
    brand: 'VoltCraft',
    images: ['https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200'],
  },
  {
    title: 'Appliance Diagnostic Sensor',
    description: 'Universal diagnostics for major kitchen appliances.',
    price: 139,
    stock: 29,
    category: 'Appliance Repair',
    brand: 'FixSense',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=1200'],
  },
  {
    title: 'Carpentry Precision Set',
    description: 'Premium woodworking hand tools and installation guides.',
    price: 85,
    stock: 71,
    category: 'Carpentry Services',
    brand: 'WoodCore',
    images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200'],
  },
];

export const bookingTemplates = [
  {
    problemTitle: 'Main Door Lock Jammed',
    problemDescription: 'The main entrance lock jams intermittently and does not rotate smoothly.',
    deviceType: 'other',
    deviceBrand: 'Yale',
    deviceModel: 'SecureMax 2',
    status: 'pending',
    estimatedCost: 80,
  },
  {
    problemTitle: 'Smart Lock Battery Drain',
    problemDescription: 'Smart lock battery drains within two days and loses WiFi connectivity.',
    deviceType: 'other',
    deviceBrand: 'DoorSetFix',
    deviceModel: 'Pro X',
    status: 'approved',
    estimatedCost: 120,
    assignedTechnician: 'David Lee',
  },
  {
    problemTitle: 'HVAC Cooling Issue',
    problemDescription: 'AC runs but does not cool the room; airflow feels weak.',
    deviceType: 'desktop',
    deviceBrand: 'ClimaSense',
    deviceModel: 'Thermo 7',
    status: 'in-progress',
    estimatedCost: 180,
    assignedTechnician: 'Sara Khan',
    adminNotes: 'Compressor inspection in progress.',
  },
  {
    problemTitle: 'Appliance Not Starting',
    problemDescription: 'Dishwasher powers on but cycle stops after 2 minutes.',
    deviceType: 'other',
    deviceBrand: 'KitchenPro',
    deviceModel: 'DW-440',
    status: 'completed',
    estimatedCost: 95,
    finalCost: 110,
    assignedTechnician: 'Asad Ali',
  },
  {
    problemTitle: 'Door Frame Alignment',
    problemDescription: 'The door frame is misaligned causing air gaps and noise.',
    deviceType: 'other',
    deviceBrand: 'Local',
    deviceModel: 'Wood Frame',
    status: 'rejected',
    rejectionReason: 'Duplicate request received for same issue.',
  },
];

export const orderStatuses = [
  { status: 'pending', paymentStatus: 'pending' },
  { status: 'paid', paymentStatus: 'paid' },
  { status: 'shipped', paymentStatus: 'paid' },
  { status: 'delivered', paymentStatus: 'paid' },
  { status: 'cancelled', paymentStatus: 'failed' },
];
