export const productCatalog = [
  {
    title: 'iPhone 15 Pro Max Clear Case',
    description: 'Military-grade drop protection with crystal clear transparency. Supports MagSafe wireless charging. Anti-yellowing technology.',
    price: 29,
    stock: 120,
    category: 'Smartphones',
    brand: 'TechShield',
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=1200'],
  },
  {
    title: 'USB-C Fast Charger 65W',
    description: 'GaN technology compact charger with dual USB-C ports. Compatible with MacBook, iPhone, Samsung, and all USB-C devices.',
    price: 45,
    stock: 85,
    category: 'Accessories',
    brand: 'PowerMax',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=1200'],
  },
  {
    title: 'Wireless Bluetooth Earbuds Pro',
    description: 'Active noise cancellation with 36-hour battery life. IPX5 water resistant. Touch controls and transparency mode.',
    price: 79,
    stock: 64,
    category: 'Audio',
    brand: 'SoundCore',
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=1200'],
  },
  {
    title: 'Laptop Stand Aluminum Ergonomic',
    description: 'Adjustable height laptop riser for 10-17 inch laptops. Ventilated design with cable management. Space gray finish.',
    price: 49,
    stock: 42,
    category: 'Laptops',
    brand: 'DeskPro',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=1200'],
  },
  {
    title: 'Mechanical Gaming Keyboard RGB',
    description: 'Hot-swappable Cherry MX switches. Per-key RGB lighting with software control. Aircraft-grade aluminum frame.',
    price: 129,
    stock: 31,
    category: 'Gaming',
    brand: 'KeyForge',
    images: ['https://images.unsplash.com/photo-1541140532154-b024d1b23b1b?w=1200'],
  },
  {
    title: 'Tempered Glass Screen Protector (3-Pack)',
    description: '9H hardness tempered glass for iPhone 15 series. Bubble-free installation with alignment frame included.',
    price: 15,
    stock: 200,
    category: 'Smartphones',
    brand: 'GlassGuard',
    images: ['https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=1200'],
  },
  {
    title: 'Portable SSD 1TB USB-C',
    description: 'Read speeds up to 1050 MB/s. Shock and vibration resistant. Compatible with PC, Mac, and gaming consoles.',
    price: 99,
    stock: 38,
    category: 'Desktops',
    brand: 'DataVault',
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=1200'],
  },
  {
    title: 'Tablet Stylus Pen with Palm Rejection',
    description: 'Precision stylus for iPad and Android tablets. Magnetic attachment. Tilt sensitivity for drawing and note-taking.',
    price: 35,
    stock: 55,
    category: 'Tablets',
    brand: 'PenTech',
    images: ['https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=1200'],
  },
  {
    title: 'Wireless Gaming Mouse 16000 DPI',
    description: 'Ultra-lightweight 63g design. 16000 DPI optical sensor. 70-hour battery. Programmable side buttons.',
    price: 69,
    stock: 47,
    category: 'Gaming',
    brand: 'ClickForce',
    images: ['https://images.unsplash.com/photo-1527814050087-3793815479db?w=1200'],
  },
  {
    title: 'USB-C Hub 7-in-1 Multiport Adapter',
    description: 'HDMI 4K, USB 3.0 x2, SD/TF card reader, USB-C PD 100W pass-through. Aluminum body.',
    price: 55,
    stock: 60,
    category: 'Laptops',
    brand: 'HubMax',
    images: ['https://images.unsplash.com/photo-1625842268584-8f3296236761?w=1200'],
  },
];

export const bookingTemplates = [
  {
    problemTitle: 'iPhone Screen Cracked',
    problemDescription: 'The screen has a large crack from a drop. Touch still works but display has color artifacts in the top-right corner.',
    deviceType: 'mobile',
    deviceBrand: 'Apple',
    deviceModel: 'iPhone 14 Pro',
    status: 'pending',
    estimatedCost: 180,
  },
  {
    problemTitle: 'MacBook Not Charging',
    problemDescription: 'MacBook Pro shows no charging indicator when plugged in. Tried multiple cables and power adapters. Battery at 0%.',
    deviceType: 'laptop',
    deviceBrand: 'Apple',
    deviceModel: 'MacBook Pro 2022 M2',
    status: 'approved',
    estimatedCost: 250,
    assignedTechnician: 'Bilal Ahmed',
  },
  {
    problemTitle: 'PC Overheating & Shutting Down',
    problemDescription: 'Desktop PC shuts down randomly after 20-30 min of use. Fans are very loud. Suspect thermal paste or GPU issue.',
    deviceType: 'desktop',
    deviceBrand: 'Custom Build',
    deviceModel: 'Intel i7 + RTX 3070',
    status: 'in-progress',
    estimatedCost: 120,
    assignedTechnician: 'Sara Khan',
    adminNotes: 'Thermal paste replaced. Running stress tests to confirm GPU stability.',
  },
  {
    problemTitle: 'Samsung Tablet Touchscreen Unresponsive',
    problemDescription: 'Bottom half of the touchscreen does not respond to touch. No cracks visible. Started after a software update.',
    deviceType: 'tablet',
    deviceBrand: 'Samsung',
    deviceModel: 'Galaxy Tab S9',
    status: 'completed',
    estimatedCost: 140,
    finalCost: 130,
    assignedTechnician: 'Asad Ali',
  },
  {
    problemTitle: 'Laptop Keyboard Keys Not Working',
    problemDescription: 'Several keys on the laptop keyboard are completely unresponsive. Liquid spill happened a week ago.',
    deviceType: 'laptop',
    deviceBrand: 'Dell',
    deviceModel: 'XPS 15 9530',
    status: 'rejected',
    rejectionReason: 'Customer cancelled — decided to purchase a new device instead.',
  },
];

export const orderStatuses = [
  { status: 'pending', paymentStatus: 'pending' },
  { status: 'paid', paymentStatus: 'paid' },
  { status: 'shipped', paymentStatus: 'paid' },
  { status: 'delivered', paymentStatus: 'paid' },
  { status: 'cancelled', paymentStatus: 'failed' },
];
